<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ExampleMinimal</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Kaldera\Kaldera.csproj"/>
        <ProjectReference Include="..\ExampleBase\ExampleBase.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SDL3-CS" Version="3.3.2.1"/>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="slangc $(ProjectDir)Shaders/default.slang -I ./ -target spirv -o $(ProjectDir)Shaders/default.spv -reflection-json $(ProjectDir)Shaders/default.spv.json"/>
    </Target>

    <Target Name="CopyShader" AfterTargets="PostBuild" DependsOnTargets="PostBuild">
        <Exec Command="cp $(ProjectDir)Shaders/default.spv $(OutDir)default.spv"/>
        <Exec Command="cp $(ProjectDir)Shaders/default.spv.json $(OutDir)default.spv.json"/>
    </Target>

</Project>
